services:

  ##########
  # RSS
  ##########
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    hostname: freshrss
    restart: unless-stopped
    networks:
      - protest-db-net
    ports:
      - "8082:80"
    logging:
      options:
        max-size: 10m
    volumes:
      - ./data/freshrss-app:/var/www/FreshRSS/data
      - ./data/freshrss-extensions:/var/www/FreshRSS/extensions
    environment:
      TZ: Europe/Paris
      CRON_MIN: '*/10'
      FRESHRSS_DB_HOST: freshrss-db
      FRESHRSS_DB_PORT: 5432
      FRESHRSS_DB_BASE: freshrss-db
      FRESHRSS_DB_USER: ${DB_USER:-freshrss}
      FRESHRSS_DB_PASSWORD: ${DB_PASSWORD:-freshrss}
      FRESHRSS_DB_TYPE: pgsql
    depends_on:
      freshrss-db:
        condition: service_healthy

  freshrss-db:
    image: postgres:17
    container_name: freshrss-db
    hostname: freshrss-db
    restart: unless-stopped
    networks:
      - protest-db-net
    # Todo: close ports when debugging is done
    ports:
      - "5432:5432"
    logging:
      options:
        max-size: 10m
    volumes:
      - ./data/freshrss-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: freshrss-db
      POSTGRES_USER: ${DB_USER:-freshrss}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-freshrss}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-freshrss} -d ${POSTGRES_DB:-freshrss-db}"]
      interval: 5s
      timeout: 5s
      retries: 10

  ##########
  # AmCAT
  ##########
  amcat-frontend:
    image: ccsamsterdam/amcat4_frontend:${AMCAT4_VERSION:-latest}
    restart: unless-stopped
    ports:
      - "3030:80"
    environment:
      - AMCAT4_URL=${AMCAT4_URL}
    volumes:
      - ./amcat/Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - amcat-net
    depends_on:
      - api

  api:
    #image: ccsamsterdam/amcat4_backend:${AMCAT4_VERSION:-latest}
    image: jbgruber/amcat4_backend:mcp-beta
    restart: unless-stopped
    networks:
      - amcat-net
    environment:
      - amcat4_elastic_host=http://amcat-elasticsearch:9200
      - amcat4_host=${AMCAT4_URL}
      - FORWARDED_ALLOW_IPS=*
      - amcat4_elastic_password
      - amcat4_elastic_verify_ssl
      - amcat4_system_index
      - amcat4_auth
      - amcat4_middlecat_url
      - amcat4_admin_email
      - amcat4_mcp_enabled
    depends_on:
      amcat-elasticsearch:
        condition: service_healthy

  amcat-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.4
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'curl -s http://localhost:9200/_cluster/health | grep -vq ''"status":"red"''',
        ]
      interval: 5s
      timeout: 5s
      retries: 15
    networks:
      - amcat-net
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms${ELASTIC_MEMORY:-1g} -Xmx${ELASTIC_MEMORY:-1g}
      - path.repo=/usr/share/elasticsearch/data/snapshots
    volumes:
      - ${ELASTIC_DATA_STORAGE:-elasticsearch_data}:/usr/share/elasticsearch/data:rw
      - ${ELASTIC_SNAPSHOT_PATH:-snapshot_data}:/usr/share/elasticsearch/data/snapshots:rw

  ##########
  # RSS 2 AmCAT
  ##########
  rss2amcat:
    build: ./rss2amcat
    container_name: rss2amcat
    restart: unless-stopped
    networks:
      - protest-db-net
    logging:
      options:
        max-size: 10m
    environment:
      POSTGRES_DB: freshrss-db
      POSTGRES_USER: ${DB_USER:-freshrss}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-freshrss}
      AMCAT_KEY: ${AMCAT_KEY}
      AMCAT_API: ${AMCAT_API}
    command: sh -c "while true; do Rscript rss2amcat.r; sleep 3600; done"
    depends_on:
      freshrss-db:
        condition: service_healthy

  ##########
  # Hydrate docs
  ##########
  paperboy:
    build: ./paperboy
    container_name: paperboy2amcat
    restart: unless-stopped
    networks:
      - protest-db-net
    logging:
      options:
        max-size: 10m
    environment:
      AMCAT_KEY: ${AMCAT_KEY}
      AMCAT_API: ${AMCAT_API}
    command: sh -c "while true; do Rscript paperboy.r; sleep 3700; done"
    depends_on:
      freshrss-db:
        condition: service_healthy

  ##########
  # LLM annotation
  ##########
  rollama:
    build: ./llm-annotation
    container_name: rollama
    restart: unless-stopped
    networks:
      - protest-db-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      options:
        max-size: 10m
    environment:
      AMCAT_KEY: ${AMCAT_KEY}
      AMCAT_API: ${AMCAT_API}
      OLLAMA: ${OLLAMA:-http://host.docker.internal:11434}
    command: sh -c "while true; do Rscript llm-extraction.r; sleep 3700; done"
    depends_on:
      freshrss-db:
        condition: service_healthy

networks:
  protest-db-net:
  amcat-net:

volumes:
  elasticsearch_data:
  snapshot_data:
