services:
  frontend:
    image: ccsamsterdam/amcat4_frontend:${AMCAT4_VERSION:-latest}
    restart: unless-stopped
    expose:
      - "80"
    environment:
      - AMCAT4_URL=${AMCAT4_URL}
    networks:
      - amcat-net
    depends_on:
      - api

  api:
    image: ccsamsterdam/amcat4_backend:${AMCAT4_VERSION:-latest}
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - amcat-net
    environment:
      - amcat4_elastic_host=http://elasticsearch:9200
      - amcat4_host=${AMCAT4_URL}
      - FORWARDED_ALLOW_IPS=*
      - amcat4_elastic_password
      - amcat4_elastic_verify_ssl
      - amcat4_system_index
      - amcat4_auth
      - amcat4_middlecat_url
      - amcat4_admin_email
    depends_on:
      elasticsearch:
        condition: service_healthy

  elasticsearch-init:
    image: busybox
    user: root
    command: chown -R 1000:0 /snapshots
    volumes:
      - ${ELASTIC_SNAPSHOT_PATH:-snapshot_data}:/snapshots

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.4
    restart: unless-stopped
    depends_on:
      elasticsearch-init:
        condition: service_completed_successfully
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'curl -s http://localhost:9200/_cluster/health | grep -vq ''"status":"red"''',
        ]
      interval: 5s
      timeout: 5s
      retries: 15
    networks:
      - amcat-net
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms${ELASTIC_MEMORY:-1g} -Xmx${ELASTIC_MEMORY:-1g}
      - path.repo=/usr/share/elasticsearch/data/snapshots
    volumes:
      - ${ELASTIC_DATA_STORAGE:-elasticsearch_data}:/usr/share/elasticsearch/data:rw
      - ${ELASTIC_SNAPSHOT_PATH:-snapshot_data}:/usr/share/elasticsearch/data/snapshots:rw

networks:
  amcat-net:

volumes:
  elasticsearch_data:
  snapshot_data:
